### ISSUE TITLE
*..measures.npz

### ISSUE THREAD

**Issue by sakalu** [GlobalFishingWatch/vessel-scoring#73]
Hi,
I am wondering where I could find the following files. Thanks!

kristina_longliner.measures.npz
kristina_trawl.measures.npz
kristina_ps.measures.npz
classified-filtered.measures.npz
slow-transits.measures.npz'

**Comment by bitsofbits** [comment]
@sakalu , they are created from the files in the `training-data` repo using the commands in `scripts\commands_to_add_measures.txt`.

**Comment by sakalu** [comment]
> @sakalu , they are created from the files in the `training-data` repo using the commands in `scripts\commands_to_add_measures.txt`.

@bitsofbits 

Hi Tim,

Thanks for your reply.

Yes, I do check the commands in 'scripts\commands_to_add_measures.txt' and found that I need the 5 files (slow-transits.npz, new_transits.npz, kristina_trawl.npz, kristina_ps.npz, kristina_longliner.npz) to create all the *.measures.npz files. However, I can't find these 5 files in the `training-data` repo. Is it correct?  Thanks!

Regards,
Saka

Do you mean that in the training-data repo

**Comment by bitsofbits** [comment]
@sakalu, that's right. I'm not sure exactly why the names don't exactly don't line up (I haven't run this in quite some time!), but false_positives should map to slow_transits and new_transits.

**Comment by sakalu** [comment]
> @sakalu, that's right. I'm not sure exactly why the names don't exactly don't line up (I haven't run this in quite some time!), but false_positives should map to slow_transits and new_transits.
@bitsofbits 

Hi Tim,

Thanks for your reply.  

I have use the commands in "scripts\commands_to_add_measures.txt", but got the error message below, do you think this might also be due to my Windows OS? Thanks!

=========================================
Traceback (most recent call last):

  File "scripts/add_measures.py", line 33, in <module>

    res = vessel_scoring.utils.messages_to_numpy(messages, len(orig))

  File "D:\Global Fishing Watch\vessel-scoring\vessel_scoring\utils.py", line 124, in messages_to_numpy

    for i, message in enumerate(messages):

  File "D:\Global Fishing Watch\vessel-scoring\vessel_scoring\add_measures.py", line 178, in process

    for self.middleidx, self.middle in self.middleIn:

  File "D:\Global Fishing Watch\vessel-scoring\vessel_scoring\add_measures.py", line 124, in load_lines

    for idx, line in enumerate(in_file):

  File "D:\Global Fishing Watch\vessel-scoring\vessel_scoring\add_measures.py", line 178, in process

    for self.middleidx, self.middle in self.middleIn:

  File "D:\Global Fishing Watch\vessel-scoring\vessel_scoring\add_measures.py", line 124, in load_lines

    for idx, line in enumerate(in_file):

  File "D:\Global Fishing Watch\vessel-scoring\vessel_scoring\add_measures.py", line 178, in process

    for self.middleidx, self.middle in self.middleIn:

  File "D:\Global Fishing Watch\vessel-scoring\vessel_scoring\add_measures.py", line 124, in load_lines

    for idx, line in enumerate(in_file):

  File "D:\Global Fishing Watch\vessel-scoring\vessel_scoring\add_measures.py", line 178, in process

    for self.middleidx, self.middle in self.middleIn:

  File "D:\Global Fishing Watch\vessel-scoring\vessel_scoring\add_measures.py", line 124, in load_lines

    for idx, line in enumerate(in_file):

  File "D:\Global Fishing Watch\vessel-scoring\vessel_scoring\add_measures.py", line 178, in process

    for self.middleidx, self.middle in self.middleIn:

  File "D:\Global Fishing Watch\vessel-scoring\vessel_scoring\add_measures.py", line 124, in load_lines

    for idx, line in enumerate(in_file):

  File "D:\Global Fishing Watch\vessel-scoring\vessel_scoring\add_measures.py", line 178, in process

    for self.middleidx, self.middle in self.middleIn:

  File "D:\Global Fishing Watch\vessel-scoring\vessel_scoring\add_measures.py", line 124, in load_lines

    for idx, line in enumerate(in_file):

  File "D:\Global Fishing Watch\vessel-scoring\vessel_scoring\add_measures.py", line 183, in process

    self.startidx, self.start = self.startIn.next()

AttributeError: 'generator' object has no attribute 'next'

**Comment by redhog** [comment]
@sakalu That's a python2 vs python3 problem.

**Comment by sakalu** [comment]
> @sakalu That's a python2 vs python3 problem.

@redhog 

Hi Egil,

Thank you for your reply to let me know that this is caused by python version.

I would like to take this opportunity to ask if you have ever seen this problem of generating the training labelled data as my discussion with Tim in the following link? 

Thanks!

Regards,
Saka
==========================================================
https://globalfishingwatch.force.com/gfw/s/question/0D51Q00006TRgRm/hi-good-day-i-would-like-to-start-a-project-to-predict-each-fishing-vessels-behaviour-regarding-fishing-or-nonfishing-on-its-tracks1oid=00D36000000rXJo&s1nid=0DB36000000Ha9f&emkind=chatterCommentNotification&s1uid=0051Q00000TsexO&emtm=1582640442857&fromEmail=1&s1ext=0
